### ISSUE TITLE
cannot import name 'HelloServerServer'

### ISSUE THREAD

**Issue by cedynia** [elpaso/qgis-helloserver#1]
Hi, I just wanted to start a HelloServer plugin, but It's not possible due to an import error. Could you give me some tips about it? Here is a full log:

`
09:20:03 INFO Server[12865]: Qgis Server Settings: 

09:20:03 INFO Server[12865]:   - QGIS_OPTIONS_PATH / '' (Override the default path for user configuration): '' (read from DEFAULT_VALUE)
09:20:03 INFO Server[12865]:   - QGIS_SERVER_PARALLEL_RENDERING / '/qgis/parallel_rendering' (Activate/Deactivate parallel rendering for WMS getMap request): 'false' (read from DEFAULT_VALUE)
09:20:03 INFO Server[12865]:   - QGIS_SERVER_MAX_THREADS / '/qgis/max_threads' (Number of threads to use when parallel rendering is activated): '-1' (read from DEFAULT_VALUE)
09:20:03 
INFO Server[12865]:   - QGIS_SERVER_LOG_LEVEL / '' (Log level): '0' (read from ENVIRONMENT_VARIABLE)
09:20:03 
INFO Server[12865]:   - QGIS_SERVER_LOG_FILE / '' (Log file): '/var/log/qgis/qgisserver.log' (read from ENVIRONMENT_VARIABLE)
09:20:03 INFO Server[12865]:   - QGIS_SERVER_LOG_STDERR / '' (Activate/Deactivate logging to stderr): 'false' (read from DEFAULT_VALUE)
09:20:03 
INFO Server[12865]:   - QGIS_PROJECT_FILE / '' (QGIS project file): '' (read from DEFAULT_VALUE)
09:20:03 
INFO Server[12865]:   - MAX_CACHE_LAYERS / '' (Specify the maximum number of cached layers): '100' (read from DEFAULT_VALUE)
09:20:03 INFO Server[12865]:   - QGIS_SERVER_CACHE_DIRECTORY / '/cache/directory' (Specify the cache directory): '//.local/share/QGIS/QGIS3/profiles/default/cache' (read from DEFAULT_VALUE)
09:20:03 INFO Server[12865]:   - QGIS_SERVER_CACHE_SIZE / '/cache/size' (Specify the cache size): '52428800' (read from DEFAULT_VALUE)
09:20:03 INFO Server[12865]: Ini file used to initialize settings: /.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
09:20:03 
INFO Server[12865]: cacheDirectory: /.local/share/QGIS/QGIS3/profiles/default/cache/
09:20:03 
INFO Server[12865]: maximumCacheSize: 52428800
09:20:03 INFO Server[12865]: Prefix  PATH: /usr
09:20:03 
INFO Server[12865]: Plugin  PATH: /usr/lib/qgis/plugins
09:20:03 
INFO Server[12865]: PkgData PATH: /usr/share/qgis
09:20:03 
INFO Server[12865]: User DB PATH: //.local/share/QGIS/QGIS3/profiles/default/qgis.db
09:20:03 
INFO Server[12865]: Auth DB PATH: /home/qgis/qgisserverdb/qgis-auth.db
09:20:03 
INFO Server[12865]: SVG PATHS: /usr/share/qgis/svg////.local/share/QGIS/QGIS3/profiles/default/svg/
09:20:03 WARNING [12865]: Adding service SampleService 1.0
09:20:03 WARNING [12865]: Adding service WCS 1.0.0
09:20:03 WARNING [12865]: Adding service WFS 1.1.0
09:20:03 WARNING [12865]: Adding service WMS 1.3.0
09:20:03 WARNING [12865]: Adding service WMTS 1.0.0
09:20:03 
INFO Server[12865]: Server initialized
09:20:03 
INFO /tmp/buildd/qgis-3.4.2+14stretch/src/server/qgsserverplugins.cpp[12865]: load library /usr/lib/qgispython (3.4.2)
09:20:03 
INFO /tmp/buildd/qgis-3.4.2+14stretch/src/server/qgsserverplugins.cpp[12865]: Python support library loaded successfully.
09:20:04 WARNING Python error[12865]: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 577, in startServerPlugin
    server_plugins[packageName] = package.serverClassFactory(serverIface)
  File "/home/qgis/plugins/HelloServer/__init__.py", line 14, in serverClassFactory
    

from HelloServer import HelloServerServer
ImportError: 
	cannot import name 'HelloServerServer'

09:20:04 WARNING Couldn't load server plugin HelloServer due to an error when calling its serverClassFactory() method[12865]: Couldn't load server plugin HelloServer due to an error when calling its serverClassFactory() method

ImportError: cannot import name 'HelloServerServer'

Traceback (most recent call last):
 

 File "/usr/lib/python3/dist-packages/qgis/utils.py", line 577, in startServerPlugin
    server_plugins[packageName] = package.serverClassFactory(serverIface)
  File "/home/qgis/plugins/HelloServer/__init__.py", line 14, in serverClassFactory
    from HelloServer import HelloServerServer
ImportError: cannot import name 'HelloServerServer'

Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]

QGIS version: 3.4.2-Madeira Madeira, 5645791

Python Path:

/usr/share/qgis/python//.local/share/QGIS/QGIS3/profiles/default/python/home/qgis/plugins//.local/share/QGIS/QGIS3/profiles/default/python/plugins/usr/share/qgis/python/plugins/usr/lib/python35.zip/usr/lib/python3.5/usr/lib/python3.5/plat-x86_64-linux-gnu/usr/lib/python3.5/lib-dynload/usr/local/lib/python3.5/dist-packages/usr/lib/python3/dist-packages

09:20:04 CRITICAL Server[12865]: Error loading server plugin HelloServer
09:20:04 
INFO Server[12865]: No server python plugins are available
09:20:04 INFO Server[12865]: ******************** New request ***************
09:20:04 INFO Server[12865]: REMOTE_ADDR: 127.0.0.1
09:20:04 INFO Server[12865]: HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
09:20:04 INFO Server[12865]: SERVICE:HELLO
09:20:04 INFO Server[12865]: Using default configuration file path: /usr/lib/cgi-bin/admin.sld
09:20:04 WARNING [12865]: Service HELLO is not registered
09:20:04 INFO Server[12865]: Request finished in 8 ms
`

**Comment by freddy34** [comment]
to solve I rewrote
```
from HelloServer import HelloServerServer
```
to
```
from .HelloServer import HelloServerServer
```
but now I receive following error
```
TypeError: QgsServerInterface.registerFilter(): argument 1 has unexpected type 'sip.wrappertype'
```
I am working with:
- 18.04.4 LTS (Bionic Beaver)
- QGIS 3.12 
- Qt 5.9.5
- Python 3.6.9

**Comment by elpaso** [comment]
Sorry, I missed this, it should be fixed now, there are more examples tested with QGIS 3 at: https://github.com/elpaso/qgis3-server-vagrant/tree/master/resources/web/plugins
